tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"
tap "heroku/brew"
tap "AdoptOpenJDK/openjdk"

brew "awscli"
brew "gpg"
brew "stern"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kubectx"
brew "rbenv"
brew "nodenv"
brew "pyenv"
brew "golang"
brew "antigen"
brew "htop"
brew "coreutils"
brew "jenv"
brew "watchman"
brew "jq"
brew "aws-iam-authenticator"
brew "heroku"
brew "travis"

cask "1password"
cask "adoptopenjdk11"
cask "charles"
cask "iterm2"
cask "jetbrains-toolbox"
cask "sublime-text"
cask "docker"
cask "google-chrome"
cask "caffeine"
cask "franz"
cask "font-inconsolata-dz-for-powerline"
cask "zoomus"
cask "spotify"
cask "dropbox"
cask "cyberduck"
cask "tuple"
cask "visual-studio-code"


mas "GIPHY Capture", id: 668208984
